### ISSUE TITLE
tests: remove need for Docker

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#132]
Usage of Docker is a bit of an anti-pattern IMO, because it actually makes it harder to run the tests in environments where you don't have Docker (such as inside `rpmbuild`). Luckily the bats tests aren't *too* specific to Docker.

* [ ] Make a nice way of getting the right version of our various testing dependencies.
* [ ] Set up a pulling script for images that operates outside of Docker.
* [ ] Clean up the weird mess of environment variable passing in the Makefile.
* [ ] (optional) Make testing more modular so that you can run all tests that don't require internet (or something).

The only downside to doing this is that the CI will no longer be running inside openSUSE so we can't make sure our packages are sane (the upside is that we no longer have to get packages into OBS in order to test with them on the CI).

Also Docker is the main reason that #131 is necessary.

**Comment by vrothberg** [comment]
Regarding list item 4 (modular tests): I'm mot sure if it's already possible, but in case not, I'd love to have a way to run a set of user-specified bats tests. That's especially helpful when testing newly implemented functionality and can safe a huge amount of time.

**Comment by cyphar** [comment]
You can use `bats` to run a single test file, but I think the only "real" solution would be to write some patches to upstream bats to allow you to specify something like Go's `-test.run`. But we should probably make `hack/test-integration.sh` allow you to specify individual files.
