### ISSUE TITLE
umoci needs a logo

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#165]
Since we live in `$current_year` I guess every project has to have a logo. If any designer is interested in submitting a logo for `umoci` I'd be happy to hear it. The name comes from "dipping" something (in Serbian) so do with that what you will. I also believe it means eyelashes in another European language.

**Comment by cyphar** [comment]
@maxbailey That looks awesome! Can you provide it under a free license (CC-BY or Apache 2.0 or similar) so that I can use it in the project? Thanks!

**Comment by maxbailey** [comment]
@cyphar Absolutely.

https://github.com/maxbailey/opensuse-umoci-logo

**Comment by maxbailey** [comment]
That works for me!
