### ISSUE TITLE
clean up after failed unpack

### ISSUE THREAD

**Issue by hallyn** [openSUSE/umoci#174]
If you 'umoci unpack --image x:y dest', and there is an error in the x:y config, then dest will remain on disk, partially unpacked.  There may be reasons not to, but offhand it seems most intuitive to clean up.

**Comment by cyphar** [comment]
Yes, that makes sense. Especially since if you're an unprivileged user then `rm -rf` might not actually work, and you need `umoci` to be clever about emulating `CAP_DAC_OVERRIDE`.

**Comment by hallyn** [comment]
Right.  Well you can "just" do the equivalent of

bottom=$(awk -F: '/serge/ { print $2 }' /etc/subuid)
range=$(awk -F: '/serge/ { print $3 }' /etc/subuid)
lxc-userns-exec -m b:0:$(id-u):1 -m b:1:${bottom}:${range} rm -rf rootfs

but not having to do that is so much nicer :)
