### ISSUE TITLE
Unpack by layer digest?

### ISSUE THREAD

**Issue by hallyn** [openSUSE/umoci#193]
Let's say I have a tag for an image that has 3 fs layers.  I'd like to unpack the first or second layer, for which there is no tag.

Is there currently a way to accomplish this?  The first is just an untar, but the second involves playing with whiteouts, so it would be really nice if umoci allowed it, although I do understand it may be a discouraged thing to do.

**Comment by cyphar** [comment]
Not yet, but this is the use-case I was thinking of when I proposed `umoci raw unpack` in #23.

**Comment by hallyn** [comment]
Quoting Aleksa Sarai (notifications@github.com):
> Not yet, but this is the use-case I was thinking of when I proposed `umoci raw unpack` in #23.

Awesome.  I think I'll require at least that before stacker can proceed.
(I'm willing to shell out to umoci cmdline API while waiting for the
library API, but not to do the same fugly manual diff+whiteout as
lapck does :)

So I'll focus on lpack lvm support in the meantime, until I get
restless.

Thanks!

**Comment by cyphar** [comment]
```
# runtime: address space conflict: map(0xc420100000) = 0x7f7311cb0000
# fatal error: runtime: address space conflict
```

Looks like some weird Go runtime bug to me. Restarting the test.

**Comment by cyphar** [comment]
`umoci raw unpack-layer` now exists, and can be used for this purpose.
