### ISSUE TITLE
umoci repack --refresh-bundle

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#196]
One usecase that @jonboulle had was that they want to avoid having to do something like:

```
% umoci repack --image blah:tag bundle_1
% umoci unpack --image blah:tag bundle_2
```

This could be combined into an operation that updates the state of `bundle` as though `umoci unpack` created said bundle. This just comes down to updating the `mtree` manifest and the descriptor path in `umoci.json`. The workflow would then just be:

```
% umoci repack --image blah:tag --refresh-bundle bundle_1
```

**Comment by cyphar** [comment]
This could be thought of as the inverse to `umoci revert` #172.

**Comment by jonboulle** [comment]
@cyphar feel free to assign this to me

**Comment by cyphar** [comment]
GitHub won't let me assign you, since you're not a member of the openSUSE org (you can always request to get added, but that'd take longer than the patch :P). So I'll just assign you in my head:

+assign @jonboulle :smile_cat:

**Comment by jonboulle** [comment]
@cyphar I'd be glad to be added to the openSUSE team or just as a collaborator on this repo if that's a possibility.

**Comment by cyphar** [comment]
D'oh, I forgot about adding collaborators. Invite sent.

*If you want to join the openSUSE GitHub, I think you need to be a [member](https://en.opensuse.org/openSUSE:Members) and then request it but I might just be able to add you to a separate team (not sure if I have the rights for that).*
