### ISSUE TITLE
make whiteout handling spec-compliant

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#224]
At the moment, our handling of whiteout files in layers isn't correct. According to the spec, whiteouts need to be applied *before* anything else in the archive. However, this leads us to a dilemma. The only way to figure out what items are present in an archive is to read the whole thing into memory (bad) or to require that the archive be seekable (also bad) in order for us to scan over the archive twice (once to collect the whiteouts, and the second time to apply the legitimately "new" files).

But in short we need to implement a few key things:

* Apply whiteouts before all other entries.
* Add support for `.wh..wh..opq`.
* Refuse to create a layer if a (real) file has `.wh.` as a prefix.

**Comment by cyphar** [comment]
Another option is to track what files we've already seen in the archive, and then be Very Clever™ about what we remove with whiteout files. While this is easy for `.wh.`, it will be quite difficult for `.wh..wh..opq` given that we cannot just do `RemoveAll` in this case.

**Comment by wking** [comment]
On Wed, Jan 10, 2018 at 02:06:53AM -0800, Aleksa Sarai wrote:
> Another option is to track what files we've already seen in the
> archive, and then be Very Clever™ about what we remove with whiteout
> files. While this is easy for `.wh.`, it will be quite difficult for
> `.wh..wh..opq` given that we cannot just do `RemoveAll` in this
> case.

Once you've tracked all the paths you've already seen in the archive,
isn't the Very Clever logic just:

  Recursively remove the parent of .wh..wh..opq, except for paths in
  your already-seen list and their ancestors.

With tar entries like:

  a/b/c/foo
  a/.wh..wh..opq

that would be:

  Recursively remove a, except for a/b/c/foo and its ancestors (a/b/c,
  a/b, and a).

[1]: https://github.com/opencontainers/image-spec/blob/v1.0.1/layer.md#whiteouts

**Comment by cyphar** [comment]
On 2018-01-10, W. Trevor King <reply@reply.github.com> wrote:
> On Wed, Jan 10, 2018 at 02:06:53AM -0800, Aleksa Sarai wrote:
> > Another option is to track what files we've already seen in the
> > archive, and then be Very Clever™ about what we remove with whiteout
> > files. While this is easy for `.wh.`, it will be quite difficult for
> > `.wh..wh..opq` given that we cannot just do `RemoveAll` in this
> > case.
> 
> Once you've tracked all the paths you've already seen in the archive,
> isn't the Very Clever logic just:
> 
>   Recursively remove the parent of .wh..wh..opq, except for paths in
>   your already-seen list and their ancestors.

Yes, but the problem (or rather "the inconvenience") is that you can't
just use RemoveAll at that point, because RemoveAll doesn't accept
filters. But yes, that is how I would implement the Very Clever™ logic
for doing this in a single-pass.

My only concern is that the spec specifically describes this process as
though the "intended" workflow is to sort the entries before you operate
on them (though I know this wasn't the intention, since Vincent was
talking about single-pass implementations at the time of writing).

-- 
Aleksa Sarai
Senior Software Engineer (Containers)
SUSE Linux GmbH
<https://www.cyphar.com/>

**Comment by wking** [comment]
On Wed, Jan 10, 2018 at 03:08:02PM -0800, Aleksa Sarai wrote:
> My only concern is that the spec specifically describes this process as
> though the "intended" workflow is to sort the entries before you operate
> on them (though I know this wasn't the intention, since Vincent was
> talking about single-pass implementations at the time of writing).

The spec SHOULDs *layer-generators* to put their whiteouts early [1].
If that was a MUST, you wouldn't have to record the set of
previously-seen paths.  Having the SHOULD allows lazy generators at
the cost of the unpacker logic discussed here.  I read the “regardless
of the order” line [2] as a semantic clarification, not as an
implementation suggestion.  Keeping a list of previously-seen entries
seems like the sane implementation when you don't have a seekable
archive.  And even if your archive was seekable, keeping a list of
previously-seen entries (leaning on memory to save on I/O) is probably
a better design decision for many users.

[1]: https://github.com/opencontainers/image-spec/blame/v1.0.1/layer.md#L275
[2]: https://github.com/opencontainers/image-spec/blame/v1.0.1/layer.md#L264

**Comment by cyphar** [comment]
I forgot to handle this part (in the case of ordinary whiteouts) in #229. Shouldn't be /too/ bad to handle (since it'll make `.wh..wh..opq` just a special case of `.wh.DIRECTORY` that doesn't remove the directory itself -- but we have to do the "simple" case for files).

> Apply whiteouts before all other entries.
