### ISSUE TITLE
Performance improvement for gunzip

### ISSUE THREAD

**Issue by flx42** [openSUSE/umoci#225]
`compress/gzip` is not as fast as it could be: https://github.com/golang/go/issues/23154
Since it probably won't improve in the Go standard library anytime soon, should we consider other options in the meantime?

Here's a test case I have:
```
mkdir -p tmp
sudo mount -t tmpfs tmpfs tmp/
cd tmp
skopeo copy docker://tensorflow/tensorflow:1.5.0-devel-gpu-py3 oci:.:1.5.0-devel-gpu-py3
time umoci unpack --rootless --image .:1.5.0-devel-gpu-py3 ./out
```

With the current code (64703df667276ceb1bb0cb70a0e46b1d7eab2355), I get:
```
real    1m0.168s
user    0m48.277s
sys     0m13.883s
```

By replacing `"compress/gzip"` with `gzip "github.com/youtube/vitess/go/cgzip"`, I get:
```
real    0m46.319s
user    0m34.472s
sys     0m13.718s
```
We could also explore other options, even piping to `gunzip(1)` might prove faster.

Thoughts?
Would that be relevant for you @hallyn @tych0?

**Comment by tych0** [comment]
On Thu, Feb 08, 2018 at 12:51:12AM +0000, Felix Abecassis wrote:
> `compress/gzip` is not as fast as it could be: https://github.com/golang/go/issues/23154
> Since it probably won't improve in the Go standard library anytime soon, should we consider other options in the meantime?
> 
> Here's a test case I have:
> ```
> mkdir -p tmp
> sudo mount -t tmpfs tmpfs tmp/
> cd tmp
> skopeo copy docker://tensorflow/tensorflow:1.5.0-devel-gpu-py3 oci:.:1.5.0-devel-gpu-py3
> time umoci unpack --rootless --image .:1.5.0-devel-gpu-py3 ./out
> ```
> 
> With the current code (64703df667276ceb1bb0cb70a0e46b1d7eab2355), I get:
> ```
> real    1m0.168s
> user    0m48.277s
> sys     0m13.883s
> ```
> 
> By replacing `"compress/gzip"` with `gzip "github.com/youtube/vitess/go/cgzip"`, I get:
> ```
> real    0m46.319s
> user    0m34.472s
> sys     0m13.718s
> ```
> We could also explore other options, even piping to `gunzip(1)` might prove faster.
> 
> Thoughts?
> Would that be relevant for you @hallyn @tych0?

Sure, any speedup is good in my book. +1 :)

**Comment by jonboulle** [comment]
https://www.youtube.com/watch?v=quOI_djS8oc

**Comment by cyphar** [comment]
I don't have a problem with switching to a faster `gzip` library -- as long as we can use a release tag for vendoring, and it has been fuzzed (or is otherwise tested).

**Comment by cyphar** [comment]
@flx42 At the moment I'm waiting on the rename of all imports in `vitess` to have a release. Is there any timeframe for the next release, or should I just pull the old library and handle it later?

**Comment by flx42** [comment]
Sorry, I don't know.

**Comment by cyphar** [comment]
All good. In that case I'm just going to use the latest release. See #233.
