### ISSUE TITLE
umoci: implement raw-unpack

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#23]
This is like `unpack` except it just does a simple extraction of a given layer diff blob (no `mtree` or `config.json`). This probably will end up being in a set of `raw-*` subcommands that are more hardcore versions of the nice interfaces.

**Comment by wking** [comment]
On Sun, Nov 06, 2016 at 09:29:23AM -0800, Aleksa Sarai wrote:
> This is like `unpack` except it just does a simple extraction of a
> given layer diff blob.

My plan for this was to teach ‘oci-unpack’ to handle layers.  So:

  $ oci-unpack --ref v1.0 source.tar dest

(with v1.0 referencing a manifest(-list)) will unpack all the layers,
and:

  $ oci-unpack --ref layer-1 source.tar dest

(with layer-1 referencing a single layer) will unpack that single
layer.  You should also be able to skip the ref engine:

  $ oci-unpack --type application/vnd.oci.image.layer.v1.tar+gzip source.tar dest sha256:123…
