### ISSUE TITLE
go1.11 breaks mutate_test.go

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#269]
I had a feeling this would eventually happen. In `go1.11`, `archive/tar` now generates slightly different archives with our test-cases an as a result our hard-coded hashes no longer pass tests. This is what is stopping Fedora 29 (and rawhide) builds from working...

/cc @ganto

**Comment by vbatts** [comment]
omg omg

**Comment by vbatts** [comment]
omg

**Comment by cyphar** [comment]
I thought this would happen with Go 1.10 when they added support for `atime` and `mtime` generation, but that was made backwards-compatible. Go 1.11 actually generates slightly different archives now. I don't really feel like actually checking to see what's different now...

**Comment by kolyshkin** [comment]
This was workarounded in moby/moby somehow, I forgot the details but can look it up. In particular, you should now explicitly set type PAX in the header (that's the only bit I remember from the top of my head).

**Comment by cyphar** [comment]
That was the case for Go 1.10 (where they added `.Format`), was this further changed in Go 1.11?

**Comment by runcom** [comment]
looks like this was the workaround @kolyshkin right? https://github.com/moby/moby/pull/37498

**Comment by cyphar** [comment]
Right, it's because now `TypeRegA` is automatically "upgraded" to `TypeReg` [see here](https://go-review.googlesource.com/c/go/+/85656). There are several depths of rage I am experiencing while writing this, because changing the semantics in a way where you cannot get the old semantics for a core library that is used in this way is very concerning. Why on earth would you change the output for such an old specification for no strong reason -- literally every tar implementation has to deal with crap output from the 1970 tar implementations! Nobody will revoke Go's POSIX compliance over using `'\0'`!

But luckily we manually set `TypeReg` in the core umoci code. The bug is in tests which set `TypeRegA` explicitly (for some reason).

**Comment by kolyshkin** [comment]
Sorry for not providing (more detailed) information earlier, here's the fix I had in mind: https://github.com/moby/moby/pull/37498 (and it looks very similar to yours:))

**Comment by cyphar** [comment]
Yeah, that's effectively the same issue I found. I was going to make a regression test, but it looks like Go 1.10 changed the `gzip` output to be slightly different -- so we got a cache break anyway and Go 1.9 produces slightly different images to Go 1.11. I would be love to know if Docker avoided this (since Go's gzip has historically been very uncontrollable in its output).

**Comment by vbatts** [comment]
God I wish we would have made all digests and sums based on non-compressed content

-------- Original Message --------

**Comment by cyphar** [comment]
Yeah, this is seriously making me question how we're going to get canonical images if we have to compress the blobs.

**Comment by cyphar** [comment]
Yeah, this is seriously making me question how we're going to get canonical images if we have to compress the blobs.

But after checking the diffs I'm even more shit scared. *The entire compressed bitstream has changed.* In `umoci` we switched to a different compression library that has faster compression speeds (#233), but the problem is the same with `compress/gzip`. `pgzip` doesn't have special version-specific code so it looks like some aspect of the computation now gives different results? Obviously `pgzip` gives different results to `compress/gzip` but that's a different topic.

With my testing, `pgzip` gives you the same results each time, but different Go versions change that result. I'm so fucking confused.
