### ISSUE TITLE
mutate: massive cleanups

### ISSUE THREAD

**Issue by cyphar** [openSUSE/umoci#96]
* [ ] `mutate` needs ... a lot of love. This will probably be punted somewhere else. @stevvooe had some interesting ideas for how to orchestrate higher level concepts -- probably should discuss things with him.

**Comment by stevvooe** [comment]
@cyphar Many ideas on mutations are in https://github.com/docker/docker/pull/27455. Much of that is docker specific, but the basic idea is:

1. Allocate a named register.
2. Load your target thing into register.
3. Modify thing.
4. Commit thing.

This avoids the complexity of inserting intermediaries into the CAS which need to be collected later. It also let's the build process be monolithic and you can generate a diff on commit.

**Comment by cyphar** [comment]
With #145 and other older changes this is pretty much done. I still would like to make `Mutator.Set` much nicer (still protecting the important internal fields, but without requiring 5 arguments when you're modifying a single struct), but that's not necessary for now. The `DescriptorPath` and `MapDescriptors` logic handles all of the cases automagically.
