### ISSUE TITLE
build from source

### ISSUE THREAD

**Issue by zeddii** [openSUSE/umoci#99]
I was wondering if there are instructions floating around on how to build umoci from a source clone ? I'm working with Open Containers in my yocto based container OS and I was about to write a similar tool to umoci when I stumbled here.

I'm already using umoci's dependencies as part of my work, so I have them packaged and ready to go .. but I've thus far been able to build oci without getting errors. I'm more of a casual go hacker, so I'm not having any luck figuring out what I've done wrong.

I'd like to build it by hand on my development system, before I start transforming that build into a bitbake recipe. I've arranged for all the source projects to be available, etc, just as I always do when integrating these sorts of packages.

So that goes back to my first question, If someone clone's umoci, what would you expect to be the steps to build it directly ?

**Comment by erikh** [comment]
I filed #100 to resolve this, let me know if it helps!

**Comment by zeddii** [comment]
Confirmed:

 [/home/bruc...SUSE/umoci]> ~/bin/umoci 
NAME:
   umoci - umoci modifies Open Container images

... Much appreciated.  With a working reference, I can generate a build system recipe.
